- name: Setup Workstation
  hosts: localhost
  tasks:
    - name: Set dynamic facts for user and OS version
      set_fact:
        username: "{{ ansible_user_id }}"
        fedora_version: "{{ ansible_distribution_major_version }}"

- import_playbook: packages.yml
- import_playbook: vim.yml
- import_playbook: nvm.yml
- import_playbook: docker.yml
- import_playbook: slack.yml
