---

- name: Set Up nvm to manage node versions
  hosts: localhost
  become_user: "{{ username }}"
  tasks:
    - name: ensure the ~/sfw directory is present
      file: path=/home/{{ username }}/sfw
            state=directory

    - name: clone nvm
      git: repo=https://github.com/creationix/nvm.git
           dest=/home/{{ username }}/sfw/nvm
           update=no

    - name: create symlink to nvm
      file: path=/home/{{ username }}/.nvm
            src=/home/{{ username }}/sfw/nvm
            state=link

    - name: set NVM_DIR in .bashrc
      lineinfile: dest=/home/{{ username}}/.bashrc
                  regexp='export NVM_DIR'
                  line='export NVM_DIR="$HOME/.nvm"'

    - name: source nvm in .bashrc
      lineinfile: dest=/home/{{ username }}/.bashrc
                  regexp='nvm\.sh'
                  line='[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"'
