- name: Update and Install packages
  hosts: localhost
  become: True
  tasks:
    - name: install rpmfusion repo
      package:
        name: "{{ item }}"
        state: present
        disable_gpg_check: true
      with_items:
        - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm
        - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm
    - name: "install basic packages"
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - bzip2
        - curl
        - readline-devel
        - redhat-rpm-config
        - zlib-devel
        - rubygems
        - fuse-encfs
        - chromium
        - python3-devel
        - python3-libselinux
        - NetworkManager-openvpn
        - NetworkManager-openvpn-gnome

    - name: "install productivity tools"
      tags: productivity
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - task
        - the_silver_searcher
        - tmux
        - tree
        - terminator
        - keepassxc
        - powerline
        - powerline-fonts

    - name: "install dev packages"
      tags: dev
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - vim
        - git
        - python-xdot
        - python3-libselinux
        - ruby-devel
        - rubygems
        - libyaml-devel
        - gcc-c++
        - make
        - tox
        - npm

    - name: "install media related packages"
      tags: media
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - vlc
        - gimp
        - ffmpeg

    - name: "install tmuxinator with ruby gem"
      shell: gem install tmuxinator
